"""initial migration - complete schema

Revision ID: 08680d2ff483
Revises:
Create Date: 2025-06-26 23:24:57.152981

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08680d2ff483"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="pain_narratives_app",
    )
    op.create_index(
        op.f("ix_pain_narratives_app_users_username"), "users", ["username"], unique=False, schema="pain_narratives_app"
    )
    op.create_table(
        "experiments_groups",
        sa.Column("experiments_group_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("system_role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("base_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dimensions", sa.JSON(), nullable=True),
        sa.Column("concluded", sa.Boolean(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["pain_narratives_app.users.id"],
        ),
        sa.PrimaryKeyConstraint("experiments_group_id"),
        schema="pain_narratives_app",
    )
    op.create_table(
        "narratives",
        sa.Column("narrative_id", sa.Integer(), nullable=False),
        sa.Column("narrative", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("seve_rube", sa.Integer(), nullable=True),
        sa.Column("seve_pat", sa.Integer(), nullable=True),
        sa.Column("disca_rube", sa.Integer(), nullable=True),
        sa.Column("disca_pat", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["pain_narratives_app.users.id"],
        ),
        sa.PrimaryKeyConstraint("narrative_id"),
        schema="pain_narratives_app",
    )
    op.create_table(
        "user_prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("prompt_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("prompt_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prompt_template", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["pain_narratives_app.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pain_narratives_app",
    )
    op.create_table(
        "experiment_group_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiments_group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiments_group_id"],
            ["pain_narratives_app.experiments_groups.experiments_group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["pain_narratives_app.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pain_narratives_app",
    )
    op.create_table(
        "experiments_list",
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("experiments_group_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("repeated", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("language_instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("with_context", sa.Boolean(), nullable=True),
        sa.Column("narrative_id", sa.Integer(), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("parsed_answers", sa.Boolean(), nullable=False),
        sa.Column("calculated_metrics", sa.Boolean(), nullable=False),
        sa.Column("extra_description", sa.JSON(), nullable=True),
        sa.Column("repo_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("exp_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiments_group_id"],
            ["pain_narratives_app.experiments_groups.experiments_group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["pain_narratives_app.narratives.narrative_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["pain_narratives_app.users.id"],
        ),
        sa.PrimaryKeyConstraint("experiment_id"),
        schema="pain_narratives_app",
    )
    op.create_table(
        "model_responses",
        sa.Column("narrative_id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("severity_score", sa.Integer(), nullable=True),
        sa.Column("disability_score", sa.Integer(), nullable=True),
        sa.Column("severity_explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("disability_explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["pain_narratives_app.experiments_list.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["pain_narratives_app.narratives.narrative_id"],
        ),
        sa.PrimaryKeyConstraint("narrative_id", "experiment_id"),
        schema="pain_narratives_app",
    )
    op.create_table(
        "questionnaires",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("experiments_group_id", sa.Integer(), nullable=False),
        sa.Column("narrative_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("questionnaire_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["pain_narratives_app.experiments_list.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiments_group_id"],
            ["pain_narratives_app.experiments_groups.experiments_group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["narrative_id"],
            ["pain_narratives_app.narratives.narrative_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["pain_narratives_app.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pain_narratives_app",
    )
    op.create_table(
        "request_response",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("request_json", sa.JSON(), nullable=True),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["pain_narratives_app.experiments_list.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pain_narratives_app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_response", schema="pain_narratives_app")
    op.drop_table("questionnaires", schema="pain_narratives_app")
    op.drop_table("model_responses", schema="pain_narratives_app")
    op.drop_table("experiments_list", schema="pain_narratives_app")
    op.drop_table("experiment_group_users", schema="pain_narratives_app")
    op.drop_table("user_prompts", schema="pain_narratives_app")
    op.drop_table("narratives", schema="pain_narratives_app")
    op.drop_table("experiments_groups", schema="pain_narratives_app")
    op.drop_index(op.f("ix_pain_narratives_app_users_username"), table_name="users", schema="pain_narratives_app")
    op.drop_table("users", schema="pain_narratives_app")
    # ### end Alembic commands ###
