"""Create ai_narratives_original schema and tables.

Authoritative replacement for the lost pain_narratives_acm_202512 schema.
Creates the schema plus 13 tables: a canonical narratives table, four real
patient tables, a denormalised master data table, expert users + feedback
tables, four LLM result tables (composite PK on participant_id, model,
run_number), and SUS results.

Hand-written rather than autogenerated because alembic's env.py is configured
to only see the pain_narratives_app schema for autogenerate. The downgrade
drops the whole schema with CASCADE.

Revision ID: 2026051500ai_narratives
Revises: 2026051100rev
Create Date: 2026-05-15
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "2026051500ai_narratives"
down_revision: Union[str, None] = "2026051100rev"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHEMA = "ai_narratives_original"


def _str(length: int | None = None) -> sa.types.TypeEngine:
    return sqlmodel.sql.sqltypes.AutoString(length=length) if length else sqlmodel.sql.sqltypes.AutoString()


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    # -------------------------------------------------------------------
    # narratives -- canonical source of narrative_id
    # -------------------------------------------------------------------
    op.create_table(
        "narratives",
        sa.Column("narrative_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("narrative_hash", _str(64), nullable=False),
        sa.Column("narrative_text", _str(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("response_id", _str(), nullable=True),
        sa.PrimaryKeyConstraint("narrative_id"),
        sa.UniqueConstraint("narrative_hash"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # real_patient_demographics
    # -------------------------------------------------------------------
    op.create_table(
        "real_patient_demographics",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("narrative_hash", _str(64), nullable=True),
        sa.Column("narrative_text", _str(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", _str(), nullable=True),
        sa.Column("marital_status", _str(), nullable=True),
        sa.Column("education_level", _str(), nullable=True),
        sa.Column("country_residence", _str(), nullable=True),
        sa.Column("country_birth", _str(), nullable=True),
        sa.Column("employment_status", _str(), nullable=True),
        sa.Column("years_with_pain", _str(), nullable=True),
        sa.Column("years_since_diagnosis", _str(), nullable=True),
        sa.Column("pain_cause_primary", _str(), nullable=True),
        sa.Column("pain_location_zones", _str(), nullable=True),
        sa.PrimaryKeyConstraint("participant_id"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # real_patient_pcs: 13 items + 3 subscales + total
    # -------------------------------------------------------------------
    pcs_item_cols = [sa.Column(f"pcs_{i:02d}", sa.Integer(), nullable=True) for i in range(1, 14)]
    op.create_table(
        "real_patient_pcs",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        *pcs_item_cols,
        sa.Column("pcs_total", sa.Integer(), nullable=True),
        sa.Column("pcs_rumination", sa.Integer(), nullable=True),
        sa.Column("pcs_magnification", sa.Integer(), nullable=True),
        sa.Column("pcs_helplessness", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("participant_id"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # real_patient_bpi: 11 items (column names mirror BPI section numbering)
    # -------------------------------------------------------------------
    bpi_item_names = [
        "bpiq11", "bpiq12", "bpiq13", "bpiq14", "bpiq15", "bpiq16", "bpiq17",
        "bpiq28", "bpiq39", "bpiq410", "bpiq511",
    ]
    bpi_item_cols = [sa.Column(n, sa.Integer(), nullable=True) for n in bpi_item_names]
    op.create_table(
        "real_patient_bpi",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        *bpi_item_cols,
        sa.Column("bpi_interference_mean", sa.Float(), nullable=True),
        sa.Column("bpi_intensity_mean", sa.Float(), nullable=True),
        sa.Column("bpi_total_mean", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("participant_id"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # real_patient_tsk: 11 items + total
    # -------------------------------------------------------------------
    tsk_item_cols = [sa.Column(f"tsk_{i:02d}", sa.Integer(), nullable=True) for i in range(1, 12)]
    op.create_table(
        "real_patient_tsk",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        *tsk_item_cols,
        sa.Column("tsk_total", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("participant_id"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # expert_users
    # -------------------------------------------------------------------
    op.create_table(
        "expert_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", _str(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("preferred_language", _str(), nullable=True),
        sa.Column("evaluation_completed", sa.Boolean(), nullable=True),
        sa.Column("assigned_narrative_01", sa.Integer(), nullable=True),
        sa.Column("assigned_narrative_02", sa.Integer(), nullable=True),
        sa.Column("assigned_narrative_03", sa.Float(), nullable=True),
        sa.Column("assigned_narrative_hash_01", _str(), nullable=True),
        sa.Column("assigned_narrative_hash_02", _str(), nullable=True),
        sa.Column("assigned_narrative_hash_03", _str(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # expert_dimension_evaluation: Likert text per dimension (severity + disability + many extended dimensions)
    # We store the core two dimensions plus a json blob for the extended set. Keeping it
    # simpler than the legacy 27-dimension hardcoded schema; the extended ratings remain
    # available via the json column for ad-hoc exploration.
    # -------------------------------------------------------------------
    op.create_table(
        "expert_dimension_evaluation",
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Float(), nullable=True),
        sa.Column("narrative_id", sa.Integer(), nullable=True),
        sa.Column("narrative_hash", _str(), nullable=True),
        sa.Column("experiments_group_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("severidad_score_alignment", _str(), nullable=True),
        sa.Column("severidad_explanation_alignment", _str(), nullable=True),
        sa.Column("severidad_usage_intent", _str(), nullable=True),
        sa.Column("discapacidad_score_alignment", _str(), nullable=True),
        sa.Column("discapacidad_explanation_alignment", _str(), nullable=True),
        sa.Column("discapacidad_usage_intent", _str(), nullable=True),
        sa.Column("extended_dimensions", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("experiment_id"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # expert_questionnaire_feedback
    # -------------------------------------------------------------------
    op.create_table(
        "expert_questionnaire_feedback",
        sa.Column("questionnaire_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Float(), nullable=True),
        sa.Column("narrative_id", sa.Integer(), nullable=True),
        sa.Column("narrative_hash", _str(), nullable=True),
        sa.Column("experiments_group_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("questionnaire_name", _str(), nullable=True),
        sa.Column("authenticity_rating", _str(), nullable=True),
        sa.Column("reasoning_adequacy_rating", _str(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("questionnaire_id"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # llm_dimension_evaluation -- composite PK (participant_id, model, run_number)
    # -------------------------------------------------------------------
    op.create_table(
        "llm_dimension_evaluation",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("model", _str(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("experiments_group_id", sa.Integer(), nullable=True),
        sa.Column("severidad_score", sa.Float(), nullable=True),
        sa.Column("severidad_explicacion", _str(), nullable=True),
        sa.Column("discapacidad_score", sa.Float(), nullable=True),
        sa.Column("discapacidad_explicacion", _str(), nullable=True),
        sa.PrimaryKeyConstraint("participant_id", "model", "run_number"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # llm_pcs_results -- composite PK
    # -------------------------------------------------------------------
    pcs_llm_items = [sa.Column(f"pcs_{i:02d}", sa.Integer(), nullable=True) for i in range(1, 14)]
    op.create_table(
        "llm_pcs_results",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("model", _str(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("experiments_group_id", sa.Integer(), nullable=True),
        sa.Column("pcs_total", sa.Integer(), nullable=True),
        sa.Column("pcs_rumination", sa.Integer(), nullable=True),
        sa.Column("pcs_magnification", sa.Integer(), nullable=True),
        sa.Column("pcs_helplessness", sa.Integer(), nullable=True),
        *pcs_llm_items,
        sa.Column("persona_name", _str(), nullable=True),
        sa.Column("persona_traits", _str(), nullable=True),
        sa.Column("model_reasoning", _str(), nullable=True),
        sa.PrimaryKeyConstraint("participant_id", "model", "run_number"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # llm_bpi_results -- composite PK
    # -------------------------------------------------------------------
    bpi_llm_items = [
        sa.Column("bpiq11", sa.Integer(), nullable=True),
        sa.Column("bpiq12", sa.Integer(), nullable=True),
        sa.Column("bpiq13", sa.Integer(), nullable=True),
        sa.Column("bpiq14", _str(), nullable=True),  # str in actual data
        sa.Column("bpiq15", sa.Integer(), nullable=True),
        sa.Column("bpiq16", sa.Integer(), nullable=True),
        sa.Column("bpiq17", sa.Integer(), nullable=True),
        sa.Column("bpiq28", sa.Integer(), nullable=True),
        sa.Column("bpiq39", sa.Integer(), nullable=True),
        sa.Column("bpiq410", sa.Integer(), nullable=True),
        sa.Column("bpiq511", sa.Integer(), nullable=True),
    ]
    op.create_table(
        "llm_bpi_results",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("model", _str(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("experiments_group_id", sa.Integer(), nullable=True),
        sa.Column("bpi_total", sa.Integer(), nullable=True),
        sa.Column("bpi_total_mean", sa.Float(), nullable=True),
        sa.Column("bpi_interference_avg", sa.Float(), nullable=True),
        sa.Column("bpi_intensity_avg", sa.Float(), nullable=True),
        sa.Column("bpi_interference_total", sa.Integer(), nullable=True),
        sa.Column("bpi_intensity_total", sa.Integer(), nullable=True),
        *bpi_llm_items,
        sa.Column("persona_name", _str(), nullable=True),
        sa.Column("persona_traits", _str(), nullable=True),
        sa.Column("model_reasoning", _str(), nullable=True),
        sa.PrimaryKeyConstraint("participant_id", "model", "run_number"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # llm_tsk_results -- composite PK
    # -------------------------------------------------------------------
    tsk_llm_items = [sa.Column(f"tsk_{i:02d}", _str(), nullable=True) for i in range(1, 12)]
    op.create_table(
        "llm_tsk_results",
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("model", _str(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("experiments_group_id", sa.Integer(), nullable=True),
        sa.Column("tsk_total", sa.Integer(), nullable=True),
        *tsk_llm_items,
        sa.Column("persona_name", _str(), nullable=True),
        sa.Column("persona_traits", _str(), nullable=True),
        sa.Column("model_reasoning", _str(), nullable=True),
        sa.PrimaryKeyConstraint("participant_id", "model", "run_number"),
        schema=SCHEMA,
    )

    # -------------------------------------------------------------------
    # sus_usability_results
    # -------------------------------------------------------------------
    sus_items = [sa.Column(f"q{i}", sa.Integer(), nullable=True) for i in range(1, 11)]
    op.create_table(
        "sus_usability_results",
        sa.Column("sus_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", _str(), nullable=True),
        sa.Column("username", _str(), nullable=True),
        sa.Column("profession", _str(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        *sus_items,
        sa.Column("sus_score", sa.Float(), nullable=True),
        sa.Column("completed_date", _str(), nullable=True),
        sa.PrimaryKeyConstraint("sus_id"),
        schema=SCHEMA,
    )


def downgrade() -> None:
    """Drop the entire schema and everything in it."""
    op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
