"""add_questionnaire_feedback_table

Revision ID: 260d578db51b
Revises: 8d3b2c1f2a00
Create Date: 2025-09-29 23:27:30.942895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260d578db51b'
down_revision: Union[str, None] = '8d3b2c1f2a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('experiments_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('narrative_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('narrative_consistency', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reasoning_adequacy', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['pain_narratives_app.experiments_list.experiment_id'], ),
    sa.ForeignKeyConstraint(['experiments_group_id'], ['pain_narratives_app.experiments_groups.experiments_group_id'], ),
    sa.ForeignKeyConstraint(['narrative_id'], ['pain_narratives_app.narratives.narrative_id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['pain_narratives_app.questionnaires.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pain_narratives_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pain_narratives_app'
    )
    op.drop_constraint(op.f('uq_assessment_feedback_experiment'), 'assessment_feedback', schema='pain_narratives_app', type_='unique')
    op.alter_column('questionnaire_prompts', 'system_role',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               schema='pain_narratives_app')
    op.alter_column('questionnaire_prompts', 'instructions',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               schema='pain_narratives_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaire_prompts', 'instructions',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='pain_narratives_app')
    op.alter_column('questionnaire_prompts', 'system_role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='pain_narratives_app')
    op.create_unique_constraint(op.f('uq_assessment_feedback_experiment'), 'assessment_feedback', ['experiment_id'], schema='pain_narratives_app', postgresql_nulls_not_distinct=False)
    op.drop_table('questionnaire_feedback', schema='pain_narratives_app')
    # ### end Alembic commands ###
