"""add_questionnaire_feedback_table

Revision ID: 260d578db51b
Revises: 8d3b2c1f2a00
Create Date: 2025-09-29 23:27:30.942895

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '260d578db51b'
down_revision: Union[str, None] = '8d3b2c1f2a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('experiments_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('narrative_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_name', sa.String(length=100), nullable=False),
    sa.Column('authenticity_rating', sa.String(length=64), nullable=False),
    sa.Column('reasoning_adequacy_rating', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['pain_narratives_app.experiments_list.experiment_id'], ),
    sa.ForeignKeyConstraint(['experiments_group_id'], ['pain_narratives_app.experiments_groups.experiments_group_id'], ),
    sa.ForeignKeyConstraint(['narrative_id'], ['pain_narratives_app.narratives.narrative_id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['pain_narratives_app.questionnaires.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pain_narratives_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pain_narratives_app'
    )
    # Skip constraint and column alterations for fresh installs
    # These were specific to production migration
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaire_feedback', schema='pain_narratives_app')
    # ### end Alembic commands ###
