"""add_questionnaire_feedback_table

Revision ID: 47f5ef239b72
Revises: 260d578db51b
Create Date: 2025-09-30 09:35:39.488934

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '47f5ef239b72'
down_revision: Union[str, None] = '260d578db51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_feedback', sa.Column('authenticity_rating', sa.String(length=64), nullable=False), schema='pain_narratives_app')
    op.add_column('questionnaire_feedback', sa.Column('reasoning_adequacy_rating', sa.String(length=64), nullable=False), schema='pain_narratives_app')
    op.alter_column('questionnaire_feedback', 'questionnaire_name',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.String(length=100),
                    existing_nullable=False,
                    schema='pain_narratives_app')
    op.drop_column('questionnaire_feedback', 'reasoning_adequacy', schema='pain_narratives_app')
    op.drop_column('questionnaire_feedback', 'narrative_consistency', schema='pain_narratives_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_feedback', sa.Column('narrative_consistency', sa.VARCHAR(length=64), autoincrement=False, nullable=False), schema='pain_narratives_app')
    op.add_column('questionnaire_feedback', sa.Column('reasoning_adequacy', sa.VARCHAR(length=64), autoincrement=False, nullable=False), schema='pain_narratives_app')
    op.alter_column('questionnaire_feedback', 'questionnaire_name',
                    existing_type=sa.String(length=100),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False,
                    schema='pain_narratives_app')
    op.drop_column('questionnaire_feedback', 'reasoning_adequacy_rating', schema='pain_narratives_app')
    op.drop_column('questionnaire_feedback', 'authenticity_rating', schema='pain_narratives_app')
    # ### end Alembic commands ###
