"""add_questionnaire_prompts_table

Revision ID: bad99e59d04b
Revises: ecc15357fad9
Create Date: 2025-09-28 15:32:40.997845

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bad99e59d04b'
down_revision: Union[str, None] = 'ecc15357fad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_prompts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('experiments_group_id', sa.Integer(), nullable=False),
        sa.Column('questionnaire_type', sa.String(length=50), nullable=False),
        sa.Column('system_role', sa.Text(), nullable=False),
        sa.Column('instructions', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['experiments_group_id'], ['pain_narratives_app.experiments_groups.experiments_group_id']),
        sa.PrimaryKeyConstraint('id'),
        schema='pain_narratives_app'
    )
    # Drop legacy table if it exists (was used in development)
    op.execute("DROP TABLE IF EXISTS pain_narratives_app.prompt_test_pcs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_test_pcs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('narrative_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('narrative_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pcs_total_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_0_nada', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_1_algo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_2_bastante', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_3_mucho', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_4_muchisimo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('pcs_scores_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_test_pcs_pkey')),
    schema='pain_narratives_app'
    )
    op.drop_table('questionnaire_prompts', schema='pain_narratives_app')
    # ### end Alembic commands ###
