"""Add preferred_language column to users table

Revision ID: da3b50e81a44
Revises: 07bdf6a47e81
Create Date: 2025-09-16 20:17:15.629715

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da3b50e81a44"
down_revision: Union[str, None] = "07bdf6a47e81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("preferred_language", sa.String(length=10), nullable=False, server_default="en"),
        schema="pain_narratives_app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "preferred_language", schema="pain_narratives_app")
    # ### end Alembic commands ###
