"""Assemble a private revision-analysis workbook from CSVs produced by notebooks 07 and 08.

Run after notebooks 07 and 08 have completed. Output:
    notebooks/outputs/revision/AINarratives_Revision_Results.xlsx
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[2]
OUT_DIR = REPO / "notebooks" / "outputs" / "revision"
WORKBOOK = OUT_DIR / "AINarratives_Revision_Results.xlsx"

SHEETS = [
    ("README", None),
    ("Table 7 - per-model agreement", "07_table7_per_model_agreement.csv"),
    ("Table 8 - inter-model", "07_table8_inter_model_agreement.csv"),
    ("Table 9 - stat comparison", "07_table9_stat_comparison_vs_anchor.csv"),
    ("Table 10a - dim x quest corr", "08_table10a_per_model_correlations.csv"),
    ("Table 10b - cross-model delta", "08_table10b_cross_model_delta.csv"),
    ("Table 10c - Q x Q vs real", "08_table10c_quest_vs_real.csv"),
    ("Table 10d - Q inter-corr", "08_table10d_quest_inter.csv"),
]


def readme_df() -> pd.DataFrame:
    return pd.DataFrame(
        [
            ["Generated by", "scripts/dev/build_revision_workbook.py"],
            ["Source CSVs", "notebooks/outputs/revision/"],
            ["", ""],
            ["Sheet", "Content"],
            ["Table 7", "Per-model agreement vs real questionnaires (MAE, RMSE, Pearson r, Spearman, Fisher 95% CI)"],
            ["Table 8", "Pairwise inter-model agreement (MAE, RMSE, Pearson r, Spearman, ICC)"],
            ["Table 9", "Wilcoxon + paired-bootstrap |error| delta of each non-anchor model vs GPT-5"],
            ["Table 10a", "Per-model 2x8 dimension-questionnaire correlations (Spearman rho, bootstrap 95% CI, FDR-corrected p)"],
            ["Table 10b", "Cross-model paired-bootstrap delta_rho anchored on GPT-5 (16 cells x non-anchor models)"],
            ["Table 10c", "Model Q x Q inter-correlations compared to real-data reference (delta rho per cell)"],
            ["Table 10d", "Questionnaire inter-correlations (PCS-BPI-TSK pairwise) for the 3 models and the real reference"],
        ],
        columns=["Field", "Value"],
    )


def main() -> None:
    if not OUT_DIR.exists():
        raise SystemExit(f"Run notebooks 07 and 08 first. Missing {OUT_DIR}")

    with pd.ExcelWriter(WORKBOOK, engine="openpyxl") as writer:
        for sheet, fname in SHEETS:
            if fname is None:
                readme_df().to_excel(writer, sheet_name=sheet, index=False)
                continue
            path = OUT_DIR / fname
            if not path.exists():
                print(f"  WARN: missing {path}; skipping sheet {sheet!r}")
                continue
            df = pd.read_csv(path)
            df.to_excel(writer, sheet_name=sheet[:31], index=False)
            print(f"  + {sheet:<32} ({len(df)} rows)")

    print(f"\nWrote {WORKBOOK}")


if __name__ == "__main__":
    main()
